

schema: volume_schema.yaml

---

world_major_gap:
  alternative: alternative
  hidden: hidden
  solid: box
  x: &newrpc_x 400 mm
  y: &newrpc_y 400 mm
  z: 400 mm
  material: potato_sio2

world_minor_gap:
  alternative: alternative
  hidden: hidden
  solid: box
  x: *newrpc_x
  y: *newrpc_y
  z: 170 mm
  material: &world_material newrpc_air

world:
  alternative: alternative
  hidden: hidden
  solid: bottom_up
  components:
    - newrpc
    - world_minor_gap
    - newrpc
    - world_major_gap
    - newrpc
    - world_minor_gap
    - newrpc
  padding: 20%
  material: *world_material

---

materials:
  - newrpc_air
  - potato_sio2
external:
  - newrpc
  - world_major_gap
